# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  create:
    types: [commit]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Install Node
      uses: actions/setup-node@v2.5.1
    - name: Install JDK
      uses: actions/setup-java@v2

    - name: Build File
      run: |
        git clone https://github.com/animeshdhakal/socketiot .
        mvn package
