# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Build SocketIoT

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Node
      uses: actions/setup-node@v2.5.1
    - name: Install JDK
      uses: actions/setup-java@v2
      with:
          java-version: '11'
          distribution: 'adopt'

    - name: Build File
      run: |
        git clone https://github.com/animeshdhakal/socketiot
        cd socketiot
        mvn package
        ls server/launcher/target/
        
    - name: Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          **.jar
